#!/usr/bin/bash

module load bcftools/1.16

cd /fs/ess/PUOM0007/gatherbeaglevcf/

bcftools merge Sample_1_imputed.vcf.gz Sample_2_imputed.vcf.gz Sample_3_imputed.vcf.gz Sample_4_imputed.vcf.gz Sample_5_imputed.vcf.gz Sample_11_imputed.vcf.gz Sample_12_imputed.vcf.gz Sample_13_imputed.vcf.gz Sample_14_imputed.vcf.gz Sample_15_imputed.vcf.gz Sample_16_imputed.vcf.gz Sample_17_imputed.vcf.gz Sample_18_imputed.vcf.gz Sample_19_imputed.vcf.gz Sample_20_imputed.vcf.gz Sample_21_imputed.vcf.gz Sample_22_imputed.vcf.gz Sample_23_imputed.vcf.gz Sample_24_imputed.vcf.gz Sample_25_imputed.vcf.gz Sample_26_imputed.vcf.gz Sample_27_imputed.vcf.gz Sample_28_imputed.vcf.gz Sample_29_imputed.vcf.gz Sample_30_imputed.vcf.gz Sample_31_imputed.vcf.gz Sample_32_imputed.vcf.gz Sample_33_imputed.vcf.gz Sample_34_imputed.vcf.gz Sample_35_imputed.vcf.gz Sample_36_imputed.vcf.gz Sample_37_imputed.vcf.gz Sample_38_imputed.vcf.gz Sample_51_imputed.vcf.gz Sample_52_imputed.vcf.gz Sample_53_imputed.vcf.gz Sample_54_imputed.vcf.gz Sample_55_imputed.vcf.gz Sample_61_imputed.vcf.gz Sample_62_imputed.vcf.gz Sample_63_imputed.vcf.gz Sample_64_imputed.vcf.gz Sample_65_imputed.vcf.gz Sample_67_imputed.vcf.gz Sample_68_imputed.vcf.gz Sample_69_imputed.vcf.gz Sample_70_imputed.vcf.gz -o cases.vcf.gz


bcftools merge Sample_6_imputed.vcf.gz Sample_7_imputed.vcf.gz Sample_8_imputed.vcf.gz Sample_9_imputed.vcf.gz Sample_10_imputed.vcf.gz Sample_39_imputed.vcf.gz Sample_40_imputed.vcf.gz Sample_41_imputed.vcf.gz Sample_42_imputed.vcf.gz Sample_44_imputed.vcf.gz Sample_45_imputed.vcf.gz Sample_46_imputed.vcf.gz Sample_47_imputed.vcf.gz Sample_48_imputed.vcf.gz Sample_49_imputed.vcf.gz Sample_50_imputed.vcf.gz Sample_56_imputed.vcf.gz Sample_57_imputed.vcf.gz Sample_58_imputed.vcf.gz Sample_59_imputed.vcf.gz Sample_60_imputed.vcf.gz Sample_71_imputed.vcf.gz Sample_72_imputed.vcf.gz Sample_73_imputed.vcf.gz Sample_75_imputed.vcf.gz Sample_76_imputed.vcf.gz Sample_80_imputed.vcf.gz Sample_81_imputed.vcf.gz Sample_82_imputed.vcf.gz Sample_83_imputed.vcf.gz Sample_84_imputed.vcf.gz Sample_85_imputed.vcf.gz Sample_86_imputed.vcf.gz Sample_87_imputed.vcf.gz Sample_88_imputed.vcf.gz Sample_89_imputed.vcf.gz Sample_90_imputed.vcf.gz Sample_91_imputed.vcf.gz Sample_92_imputed.vcf.gz Sample_93_imputed.vcf.gz Sample_94_imputed.vcf.gz Sample_95_imputed.vcf.gz Sample_96_imputed.vcf.gz Sample_97_imputed.vcf.gz Sample_98_imputed.vcf.gz Sample_99_imputed.vcf.gz Sample_100_imputed.vcf.gz Sample_101_imputed.vcf.gz Sample_102_imputed.vcf.gz Sample_103_imputed.vcf.gz Sample_104_imputed.vcf.gz Sample_105_imputed.vcf.gz Sample_107_imputed.vcf.gz Sample_108_imputed.vcf.gz Sample_109_imputed.vcf.gz -o controls.vcf.gz
